import { MachineConfig } from '@/types/machine';

export const MACHINES_CONFIG: MachineConfig[] = [
  {
    id: 'M01',
    name: '5-Axis CNC Milling Center',
    type: 'High Precision CNC',
    category: 'milling',
    line: 'Machining Cell Alpha',
    location: 'Bay 1 - North Wing',
    priority: 'critical',
    ratedPowerKw: 15.0,
    ratedVoltage: 400,
    ratedCurrent: 22.5,
    ratedRpm: 12000,
    baselineTemp: 50.0,
    baselineVibration: 2.0,
    baselineCurrent: 21.5,
    baselineNoise: 72.0,
    baselinePowerFactor: 0.94,
    thresholds: {
      tempWarning: 62.0,
      tempCritical: 75.0,
      vibWarning: 3.5,
      vibCritical: 5.5,
      currentMax: 26.0,
      minPowerFactor: 0.85,
    },
    mapPosition: { row: 1, col: 1 },
  },
  {
    id: 'M02',
    name: '400-Ton Hydraulic Stamping Press',
    type: 'Heavy Stamping Press',
    category: 'stamping',
    line: 'Press Line 01',
    location: 'Bay 1 - Central Forge',
    priority: 'critical',
    ratedPowerKw: 22.0,
    ratedVoltage: 400,
    ratedCurrent: 33.0,
    ratedRpm: 1800,
    baselineTemp: 55.0,
    baselineVibration: 2.8,
    baselineCurrent: 31.0,
    baselineNoise: 84.0,
    baselinePowerFactor: 0.92,
    thresholds: {
      tempWarning: 68.0,
      tempCritical: 80.0,
      vibWarning: 4.8,
      vibCritical: 7.0,
      currentMax: 38.0,
      minPowerFactor: 0.82,
    },
    mapPosition: { row: 1, col: 2 },
  },
  {
    id: 'M03',
    name: 'Rotary Screw Air Compressor',
    type: 'Dual-Stage Compressor',
    category: 'compressor',
    line: 'Utility Support Line',
    location: 'Utility Room 02',
    priority: 'high',
    ratedPowerKw: 18.5,
    ratedVoltage: 400,
    ratedCurrent: 27.5,
    ratedRpm: 3600,
    baselineTemp: 60.0,
    baselineVibration: 3.0,
    baselineCurrent: 26.0,
    baselineNoise: 76.0,
    baselinePowerFactor: 0.91,
    thresholds: {
      tempWarning: 72.0,
      tempCritical: 84.0,
      vibWarning: 4.5,
      vibCritical: 6.8,
      currentMax: 32.0,
      minPowerFactor: 0.80,
    },
    mapPosition: { row: 1, col: 3 },
  },
  {
    id: 'M04',
    name: 'Hydraulic Power Distribution Unit',
    type: 'Hydraulic Pumping Station',
    category: 'hydraulic',
    line: 'Hydraulics Core',
    location: 'Bay 2 - Sub-Station',
    priority: 'high',
    ratedPowerKw: 12.0,
    ratedVoltage: 400,
    ratedCurrent: 18.0,
    ratedRpm: 1500,
    baselineTemp: 48.0,
    baselineVibration: 1.8,
    baselineCurrent: 16.5,
    baselineNoise: 68.0,
    baselinePowerFactor: 0.93,
    thresholds: {
      tempWarning: 60.0,
      tempCritical: 72.0,
      vibWarning: 3.2,
      vibCritical: 4.8,
      currentMax: 22.0,
      minPowerFactor: 0.85,
    },
    mapPosition: { row: 2, col: 1 },
  },
  {
    id: 'M05',
    name: 'Electric Plastic Injection Molder',
    type: 'High-Tonnage Molding Cell',
    category: 'molding',
    line: 'Polymer Extrusion 02',
    location: 'Bay 2 - East Wing',
    priority: 'medium',
    ratedPowerKw: 25.0,
    ratedVoltage: 400,
    ratedCurrent: 38.0,
    ratedRpm: 2400,
    baselineTemp: 72.0,
    baselineVibration: 2.2,
    baselineCurrent: 35.5,
    baselineNoise: 70.0,
    baselinePowerFactor: 0.89,
    thresholds: {
      tempWarning: 84.0,
      tempCritical: 95.0,
      vibWarning: 3.8,
      vibCritical: 5.8,
      currentMax: 44.0,
      minPowerFactor: 0.78,
    },
    mapPosition: { row: 2, col: 3 },
  },
  {
    id: 'M06',
    name: 'Industrial HVAC Chiller Plant',
    type: 'Centrifugal Liquid Chiller',
    category: 'chiller',
    line: 'Climate & Process Cooling',
    location: 'Roof Facility Deck',
    priority: 'medium',
    ratedPowerKw: 16.0,
    ratedVoltage: 400,
    ratedCurrent: 24.0,
    ratedRpm: 2900,
    baselineTemp: 42.0,
    baselineVibration: 1.5,
    baselineCurrent: 22.0,
    baselineNoise: 74.0,
    baselinePowerFactor: 0.92,
    thresholds: {
      tempWarning: 55.0,
      tempCritical: 68.0,
      vibWarning: 2.8,
      vibCritical: 4.2,
      currentMax: 29.0,
      minPowerFactor: 0.84,
    },
    mapPosition: { row: 3, col: 1 },
  },
  {
    id: 'M07',
    name: 'Fume Exhaust & Scrubbing Blower',
    type: 'Centrifugal Exhaust Fan',
    category: 'blower',
    line: 'Environmental Scrubber',
    location: 'Ventilation Loft',
    priority: 'low',
    ratedPowerKw: 8.5,
    ratedVoltage: 400,
    ratedCurrent: 12.8,
    ratedRpm: 1750,
    baselineTemp: 45.0,
    baselineVibration: 2.1,
    baselineCurrent: 11.5,
    baselineNoise: 78.0,
    baselinePowerFactor: 0.88,
    thresholds: {
      tempWarning: 58.0,
      tempCritical: 70.0,
      vibWarning: 3.6,
      vibCritical: 5.2,
      currentMax: 16.0,
      minPowerFactor: 0.75,
    },
    mapPosition: { row: 3, col: 2 },
  },
  {
    id: 'M08',
    name: 'Main Assembly Infeed Conveyor',
    type: 'Variable Frequency Conveyor',
    category: 'conveyor',
    line: 'Assembly Transit Line',
    location: 'Main Logistics Corridor',
    priority: 'high',
    ratedPowerKw: 5.5,
    ratedVoltage: 400,
    ratedCurrent: 8.5,
    ratedRpm: 1200,
    baselineTemp: 38.0,
    baselineVibration: 1.2,
    baselineCurrent: 7.6,
    baselineNoise: 62.0,
    baselinePowerFactor: 0.93,
    thresholds: {
      tempWarning: 50.0,
      tempCritical: 62.0,
      vibWarning: 2.4,
      vibCritical: 3.8,
      currentMax: 11.0,
      minPowerFactor: 0.82,
    },
    mapPosition: { row: 3, col: 3 },
  },
  {
    id: 'M09',
    name: 'High-Frequency Induction Annealer',
    type: 'Electromagnetic Induction Furnace',
    category: 'heating',
    line: 'Heat Treatment Cell',
    location: 'Bay 3 - Thermal Shop',
    priority: 'medium',
    ratedPowerKw: 30.0,
    ratedVoltage: 400,
    ratedCurrent: 45.0,
    ratedRpm: 0,
    baselineTemp: 68.0,
    baselineVibration: 0.8,
    baselineCurrent: 42.0,
    baselineNoise: 58.0,
    baselinePowerFactor: 0.95,
    thresholds: {
      tempWarning: 82.0,
      tempCritical: 96.0,
      vibWarning: 2.0,
      vibCritical: 3.5,
      currentMax: 52.0,
      minPowerFactor: 0.88,
    },
    mapPosition: { row: 3, col: 4 },
  },
  {
    id: 'M10',
    name: 'Robotic Pick & Pack Palletizer',
    type: '6-Axis Articulated Robot',
    category: 'robotics',
    line: 'Packaging Outfeed',
    location: 'End of Line Cell',
    priority: 'low',
    ratedPowerKw: 4.2,
    ratedVoltage: 400,
    ratedCurrent: 6.4,
    ratedRpm: 3000,
    baselineTemp: 36.0,
    baselineVibration: 0.9,
    baselineCurrent: 5.8,
    baselineNoise: 60.0,
    baselinePowerFactor: 0.91,
    thresholds: {
      tempWarning: 48.0,
      tempCritical: 60.0,
      vibWarning: 2.2,
      vibCritical: 3.6,
      currentMax: 8.5,
      minPowerFactor: 0.80,
    },
    mapPosition: { row: 4, col: 2 },
  },
];

export const getMachineConfig = (id: string): MachineConfig | undefined => {
  return MACHINES_CONFIG.find((m) => m.id === id);
};
